config:
  http:
    timeout: 3000
  tls:
    rejectUnauthorized: false
  target: "https://api.example.com"
  plugins:
    expect: {}
    #metrics-by-endpoint: {}
  phases:
    - duration: 1
      arrivalRate: 1
  environments:
    production:
      target: "https://api.example.com"
      phases:
        - duration: 1
          arrivalRate: 1
      socketio:
        transports: ['websocket']
    staging:
      target: "https://api.example.com"
      phases:
        - duration: 1
          arrivalRate: 1
      socketio:
        transports: ['websocket']
    devshell:
      target: "https://api.example.com"
      phases:
        - duration: 1
          arrivalRate: 1
      socketio:
        transports: ['websocket']
  processor: "../processor.js"